rootProject.name = "sprintboot-kt"
include("app")
include("captcha")
include("common")
include("jwt-auth")

include("tenant")
include("core")
include("user")
include("user:user-core")
include("user:user-api")
include("tenant:tenant-api")
include("tenant:tenant-core")
include("security")
include("dict")
include("dict:dict-api")
include("dict:dict-core")
include("authorization")
include("authorization:authorization-api")
include("authorization:authorization-core")