logging:
  file: logs/dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
    level:
      root: DEBUG
      org.springframework.web: DEBUG
      guru.springframework.controllers: DEBUG
      org.ktorm: DEBUG


spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

oauth2:
  # 是否启用 OAuth2 认证
  enabled: true

  # 默认重定向 URI 模板（可选）
  default-redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

  # 默认权限范围（可选）
  default-scopes: "openid,profile,email"


server:
  servlet:
    context-path: /api
  port: ${APP_PORT}
  application:
    name: spring-boot-kt

# SpringDoc OpenAPI 配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true