logging:
  file: logs/dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
    level:
      root: DEBUG
      org.springframework.web: DEBUG
      guru.springframework.controllers: DEBUG
      org.ktorm: DEBUG


spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/web_ai
    username: root
    password: "zhang1128!"
  config.import:
    - application-auth.yml

server:
  servlet:
    context-path: /api
  port: 8081
  application:
    name: spring-boot-kt